name: Go

on:
  push:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOOS: js
      GOARCH: wasm
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
        
    - run: echo "$(go env GOROOT)/misc/wasm" >> $GITHUB_PATH

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
